CREATE TABLE ACCOUNTS
(
    ID             BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BALANCE        INTEGER,
    ACCOUNT_STATUS VARCHAR(255),
    USER_ID        BIGINT
) ENGINE = MYISAM;

CREATE TABLE FK_USER_ROLE
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
) ENGINE = MYISAM;

CREATE TABLE ROLES
(
    ID        BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME VARCHAR(255)
) ENGINE = MYISAM;

CREATE TABLE USERS
(
    ID                 BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ENCRYPTED_PASSWORD VARCHAR(255),
    FIRST_NAME         VARCHAR(255),
    USER_STATUS        VARCHAR(255)
) ENGINE = MYISAM;

ALTER TABLE ACCOUNTS
    ADD CONSTRAINT FK_ACCOUNT_TO_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID);

ALTER TABLE FK_USER_ROLE
    ADD CONSTRAINT FK_ROLE_ID_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID);

ALTER TABLE FK_USER_ROLE
    ADD CONSTRAINT FK_USER_ID_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID);