INSERT INTO ROLES VALUES(1, 'ADMIN');
INSERT INTO ROLES VALUES(2, 'ACCOUNTANT');
INSERT INTO ROLES VALUES(3, 'CUSTOMER');

INSERT INTO USERS VALUES(1, 'Egor', 'Vakulenko', 'active');
INSERT INTO USERS VALUES(2, 'Andrew', 'Kos', 'active');
INSERT INTO USERS VALUES(3, 'Vasya', 'Antonov', 'active');

INSERT INTO FK_USER_ROLE VALUES(1, 1);
INSERT INTO FK_USER_ROLE VALUES(2, 3);
INSERT INTO FK_USER_ROLE VALUES(3, 3);

INSERT INTO ACCOUNTS VALUES(1, '50050', 'active', 2);
INSERT INTO ACCOUNTS VALUES(2, '50050', 'active', 3);
INSERT INTO ACCOUNTS VALUES(3, '12345', 'active', 3);


