UPDATE ROLES SET ROLE_NAME = 'ROLE_ADMIN' WHERE ID = 1;
UPDATE ROLES SET ROLE_NAME = 'ROLE_ACCOUNTANT' WHERE ID = 2;
UPDATE ROLES SET ROLE_NAME = 'ROLE_CUSTOMER' WHERE ID = 3;

UPDATE USERS SET ENCRYPTED_PASSWORD = '$2a$04$Ff6N04uVlC0qrTSRpVTaqe5HJ1Rzd3/i6p/Hvp8DqDalCbhmROU7u' WHERE ID = 1;
UPDATE USERS SET ENCRYPTED_PASSWORD = '$2a$04$0FyGGlHgZ9kxQovOVQtkpeYExkR2tCb6R1aXws79zV2kWnqGl3h32' WHERE ID = 2;
UPDATE USERS SET ENCRYPTED_PASSWORD = '$2a$04$MuaXrxJtVy6/Jknq1ZxZtuiAJlAh5Degt8uRnCnG7CK.mxZZVlfEq' WHERE ID = 3;

UPDATE USERS SET FIRST_NAME = 'Egor' WHERE ID = 1;
UPDATE USERS SET FIRST_NAME = 'Andrew' WHERE ID = 2;
UPDATE USERS SET FIRST_NAME = 'Vasya' WHERE ID = 3;
