DROP TABLE FK_USER_ROLE;

CREATE TABLE FK_USER_ROLE
(
    ID      BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (ID, USER_ID, ROLE_ID)
) ENGINE = MYISAM;

INSERT INTO FK_USER_ROLE VALUES(1, 1, 1);
INSERT INTO FK_USER_ROLE VALUES(2, 2, 2);
INSERT INTO FK_USER_ROLE VALUES(3, 3, 3);

ALTER TABLE FK_USER_ROLE
    ADD CONSTRAINT FK_ROLE_ID_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID);

ALTER TABLE FK_USER_ROLE
    ADD CONSTRAINT FK_USER_ID_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID);