UPDATE ACCOUNTS SET ACCOUNT_STATUS = 'ACTIVE' WHERE ID = 1;
UPDATE ACCOUNTS SET ACCOUNT_STATUS = 'ACTIVE' WHERE ID = 2;
UPDATE ACCOUNTS SET ACCOUNT_STATUS = 'ACTIVE' WHERE ID = 3;

UPDATE USERS SET USER_STATUS = 'ACTIVE' WHERE ID = 1;
UPDATE USERS SET USER_STATUS = 'ACTIVE' WHERE ID = 2;
UPDATE USERS SET USER_STATUS = 'ACTIVE' WHERE ID = 3;